services:
  web:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: FastApi
    image: lab:1.0 
    ports:
      - "8000:8000"
    #env_file:
    #  - ./backend/.env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fast_api_db
      MYSQL_USER: dast_api
      MYSQL_PASSWORD: 123ab
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: